version: '2'
services:
    map:
        build: .
        command: >
            sh -c "
                python tests.py &&
                python main.py"
        volumes:
            - .:/code
        ports:
            - "8006:8006"